from os import path
import tcod

COLOR_PLAYER = tcod.Color(200, 0, 0)
COLOR_DARK_WALL = tcod.Color(50, 50, 150)
COLOR_DARK_GROUND = tcod.Color(50, 50, 150)
COLOR_LIGHT_WALL = tcod.Color(130, 110, 50)
COLOR_LIGHT_GROUND = tcod.Color(200, 180, 50)
COLOR_EXPLORED_WALL = tcod.Color(0, 0, 150)
COLOR_EXPLORED_GROUND = tcod.Color(100, 100, 150)
DEATH_COLOR = tcod.dark_red

FOV_ALGO = tcod.FOV_SHADOW
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 4

SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

MAP_WIDTH = 80
MAP_HEIGHT = 43

BAR_WIDTH = 20
PANEL_HEIGHT = SCREEN_HEIGHT - MAP_HEIGHT
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT

HP_FG_COLOR = tcod.light_red
PANEL_BG_COLOR = tcod.grey
MAX_ROOM_MONSTERS = 3

MONSTER_DIR = path.join(path.dirname(__file__), 'monsters/')
